# Site wide configuration

title:            Neal Hughes
locale:           en_US
url:              http://nealhughes.net

show_downloads: false

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Neal Hughes
  avatar: test.jpg
  bio: ""
  email: hughes.neal@gmail.com
  
minima:
  social_links:
    twitter: hughesneal1
    github: nealbob
    stackoverflow: #username
    dribbble: #username
    facebook: #username
    flickr: #username
    instagram: #username
    linkedin: #username
    pinterest: #username
    telegram: jekyll
    microdotblog: #username
    keybase: #username

    mastodon:
     - username: #username
       instance: example.com
     - username: #username
       instance: example.com

    gitlab:
     - username: #username
       instance: example.com
     - username: #username
       instance: example.com

    youtube: #username
    youtube_channel: #username
    youtube_channel_name: #username
    

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

theme: minima
